# Site settings
description: bebo-dot-dev.github.io blog
baseurl: ""
url: "https://bebo-dot-dev.github.io"

# User settings
name: joe
username: joe at bebo dot dev 
user_description: Joe Lippa at bebo.dev
user_title: c# hacker by day, c/c++ hacker by night
email: joe@bebo.dev
twitter_username: joe_lippa
github_username:  bebo-dot-dev
gplus_username:  108205719135497472486
disqus_username: jjssoftwaregithubio

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: YouTube
    external: true    
    url: https://www.youtube.com/channel/UCa_exk34O_W2tTnGeHXw5Og
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
